# Base URL of the application under test
base_url: "https://www.automationexercise.com/"

# Browsers for test execution; only Chrome and Edge supported currently
browsers:
  - chrome
  - edge

# Default implicit wait time
implicit_wait: 10
